### ISSUE TITLE
(OSX) Any Rom - Grey Bars in Full Screen

### ISSUE THREAD

**Issue by powerfulstone** [TASEmulators/desmume#596] opened 2022-10-02 16:48 UTC
[ BEGIN DESMUME TROUBLESHOOTING INFORMATION ]

App Version:  0.9.13 ARM64 NEON-A64 (LLVM-Clang v13.1.6)
Operating System: macOS v12.5 (21G72)
Model Identifier: MacBookPro18,3
ROM Name: GHOSTTRICK-E
ROM Serial: NTR-BGTE-USA

Emulation Speed: 1.00x
Auto Frame Skip: YES
SLOT-1 Device Type: Retail (Auto)
SLOT-2 Device Type: Auto
Advanced Bus-Level Timing: YES
Rigorous 3D Rendering Timing: NO
CPU Emulation Engine: Interpreter
Use Game-Specific Hacks: YES
External BIOS: NO
External Firmware: NO
GPU - Scaling Factor: 1x
GPU - Color Depth: 18-bit
3D Renderer - Engine: SoftRasterizer (HighResColor=YES, LineHack=YES, FragmentSamplingHack=NO, ThreadCount=Automatic)
3D Renderer - Enable Textures: YES
3D Renderer - Texture Deposterize: NO
3D Renderer - Texture Scaling Factor: 1x
3D Renderer - Edge Marking: YES
3D Renderer - Fog: YES
Video - Output Engine: macOS Metal GPUFamily2_v1 (Apple M1 Pro)
Audio - Output Engine: macOS Core Audio Sound Interface
Audio - Advanced SPU Logic: YES
Audio - Sound Interpolation Method: Cosine
Audio - Sound Synchronization Method: "N" Sync Method

Cheats: NO

Observed Behavior: When in full screen, DeSmuME places a grey bar above (sometimes below or to the side of the game as well), so that the game is at the bottom of the screen (bar only present in full screen).

Expected Behavior: DeSmuME does not center the game in the middle of a black screen without any bars.

[ END DESMUME TROUBLESHOOTING INFORMATION ]

> Not sure why this issue is present, I moved the same build of DeSmuME with the same settings from my previous laptop where I never had any issues. 

> Also tried going full-screen with all the roms I have, the issue is present with all of them.

**Comment by zeromus** [comment] 2022-12-04 22:42
gonna call it a dupe of #597, add any details contrariwise or otherwise over there

**Closed by zeromus** 2022-12-04 22:42 UTC
