### ISSUE TITLE
Cheat search is disabled in Linux Gtk frontend

### ISSUE THREAD

**Issue by grepwood** [TASEmulators/desmume#724] opened 2023-09-02 09:56 UTC
I've installed desmume on Gentoo Linux and immediately noticed that I can't search for memory changes in order to come up with my own cheats. Logs don't give any indication why is that happening :(

**Comment by zeromus** [comment] 2023-09-02 10:25
"can't search" "disabled" What does this mean exactly? It isn't clear

**Comment by grepwood** [comment] 2023-09-02 10:57
![obraz](https://github.com/TASEmulators/desmume/assets/4225739/2c4e9fb8-3fbd-4041-b464-eb4cec93bffa)
It means the option to actually search for cheats, is grayed out. It's disabled.

**Comment by rogerman** [comment] 2023-09-14 21:26
The Cheat Search menu option in the GTK port is disabled by design. This is because Cheat Search is currently unimplemented in the GTK port. If you need the Cheat Search feature right now, then the Windows and macOS ports are your only options.

Closing, due to the fact that there are no plans in the near future to implement this feature for GTK, unless someone familiar with GTK and Linux is willing to give it a shot.

**Closed by rogerman** 2023-09-14 21:26 UTC
