### ISSUE TITLE
Pixel scaler does not apply to main screen

### ISSUE THREAD

**Issue by preland** [TASEmulators/desmume#715] opened 2023-07-24 22:01 UTC
Whenever I use the pixel scaler, it applies to the touch screen, but not to the main screen. This is true across all games.

Platform: Intel Mac
DeSmuME version: v0.9.13

I see in the FAQ that it says to "select the window you want to change", but that is somewhat vague, as it doesn't say if both screens in a window will get changed. (Also, opening another window with only the main screen shown does not fix the issue)

Is this an error, or is there something I'm just not getting? Thanks

**Comment by rogerman** [comment] 2023-07-24 22:35
The FAQ is accurate. A "window" is the host-provided video display window that can contain NDS screens, HUD information, UI elements, and other video/display related things. A "screen" is an NDS screen within the host-provided window that is the emulated video output of the NDS. The language differentiates between screens and windows, and does not treat them interchangeably.

As for pixel scalars, these are set to specific windows and applied to all screens within the window. This allows the user to use a different pixel scalar for each window. However, pixel scalars are applied on a per-screen basis, where the main condition is that the screen was rendered at the native NDS resolution of 256x192px.

If a screen contains portions of high-resolution 3D rendering, which can happen if the user sets the GPU Scaling Factor to something higher than 1x, then that screen WILL NOT have pixel scaling applied to it since this would interfere with high-resolution 3D rendering. This is all intentional and by design. In other words, if you want to guarantee that pixel scalars apply to all screens, then you need to turn off high-resolution 3D rendering by setting GPU Scaling Factor back to 1x. That's it.

A lot of research went into the interactions between pixel scalars and high-resolution 3D rendering, and I strongly believe that Mac DeSmuME makes all of the correct design choices here. Unless there are powerful arguments against these design decisions, then I have no intention of changing this behavior, as the current behavior provides the best visual consistency and performance for zero compromise.

Closing, since this is just the user's misunderstanding, and not an actual bug.

**Closed by rogerman** 2023-07-24 22:35 UTC
