### ISSUE TITLE
Integer scaling not working properly

### ISSUE THREAD

**Issue by yontekh** [TASEmulators/desmume#592] opened 2022-09-15 01:37 UTC
When using:
- Horizontal screen layout
- Screen size ratio 1.5 - 0.5
- OpenGL display without filtering
- Fullscreen on 16:9 resolution.
DeSmuMe 0.9.14 git#58c5b33 x64-JIT SSE2. Compiled Sept 4 2022 03:29:33

The pixels on both screens aren't scaling correctly. Regardless of integer padding is enabled or not. Resulting in oval shaped pixels on the bigger screen, and a blurred smaller screen. 

What it should look like:
![image](https://user-images.githubusercontent.com/77578151/190292176-343df25c-5ac7-499f-b3b2-86afe45f9582.png)

What it looks like:
![image](https://user-images.githubusercontent.com/77578151/190292447-b7d774ca-d856-4194-b292-4c48fa738189.png)

Zoom:
![image](https://user-images.githubusercontent.com/77578151/190293088-d9fb4b54-74f2-4b9f-853b-35cd949f03b5.png)
![image](https://user-images.githubusercontent.com/77578151/190295007-7313c4d1-673a-41b3-bfde-1118591a2a5a.png)

[desmume.ini.zip](https://github.com/TASEmulators/desmume/files/9571030/desmume.ini.zip)
(Please forgive my use of a pokemon game in this example.)

**Comment by zeromus** [comment] 2022-09-15 02:20
If you have filtering appearing (and it seems you do) then it's because you've forced it in your GPU drivers, or your GPU drivers are malfunctioning, or you've told windows to do something strange with your DPI and it's scaling up the window in its own way. We aren't directing any filtering to happen unless the box is checked in the display method menu. We can't control what your OS does with our window. 

I notice a triangular seam in the green menu (you can really only see it tearing the right edge of the menu). I also notice that your degree of filtering is WAY more than I expect. Like, I see multiple grades of blending. That would be impossible with the way desmume does it; there should be only one grade of blending. Again, it's suggestive of your GPU or OS scaling things up and using a filter intended for games or cat pictures instead of getting work done.

**Closed by zeromus** 2022-09-15 02:20 UTC

**Comment by yontekh** [comment] 2022-09-15 16:48
You are absolutely right, the filtering/blur is all due to Windows DPI scaling.
I fixed that, sorry for not doing that in the first place.

However the rectangular pixels are still a thing on all 3 of my machines (Nvidia, AMD and Intel GPU) regardless.
Whenever I set screen-size-ratio to 1.5-0.5, with 'pad to integer' on, and go fullscreen, pixels are still scaling incorrectly.

![image](https://user-images.githubusercontent.com/77578151/190461101-1d266499-2f60-4aa5-b6c4-b34cba22a87f.png)


![image](https://user-images.githubusercontent.com/77578151/190461414-26bcfd10-11ea-4d7a-a1f4-12ddcbbfb461.png)

**Comment by zeromus** [comment] 2022-09-15 19:42
Pad to integer was done before the screen size ratio thing was done. I told people for years the reason stuff like that could not be done was because the code was too complex and it was impossible to do it right. Then someone finally did the screen size ratio thing. No surprise, it was done wrongly, since it combines complexly with too many other features. I think the problem is probably that the overall scaling level is not a multiple of 3 (which is what relates each individual screen size). I have to tell you to mention this bug to whoever did the screen size ratio thing. Which means it will never get fixed. Sorry, this code in desmume is UNMANAGEABLY COMPLEX and someone needs to nuke it all and redo it with all the requirements in mind.

**Comment by yontekh** [comment] 2022-09-15 22:09
Alright I appreciate your response, I understand. Thanks for taking the time to explain it to me.
I'll not use screen-size-ratio and then there is no problem.

**Comment by yontekh** [comment] 2022-09-15 22:30
I found the pull request:
https://github.com/TASEmulators/desmume/pull/158

**Comment by zeromus** [comment] 2022-09-16 00:31
what about it? it was merged
