### ISSUE TITLE
volume adjustor not working

### ISSUE THREAD

**Issue by jetaime2x** [TASEmulators/desmume#823] opened 2024-08-14 20:26 UTC
## State your operating system:
Mac

## DesMuME version
0.9.13

## Issue
I'm trying to play ace attorney while on call with my friend, but the game is so loud that I can't hear him and the volume slider in settings isnt doing anything no matter what setting i choose. Because I'm on mac i can't just turn down the application volume.

**Comment by rogerman** [comment] 2024-08-15 06:24
The volume slider in Settings is meant to set the default volume on app startup. It doesn't set the volume for the current session. This is by design.

If you want to set the volume for the current session, then adjust the volume slider under Emulation > Show Sound Settings. Alternatively, you can also adjust the volume slider in the video window's status bar, located in the lower right corner of the window.

Closing, due to user error.

**Closed by rogerman** 2024-08-15 06:24 UTC
